version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443' # Port pour HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl # Volume pour les certificats SSL
    depends_on:
      - jenkins
    networks:
      - jenkins_network

networks:
  jenkins_network:

volumes:
  jenkins_home:
