version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_network

nginx:
  image: nginx:latest
  container_name: nginx
  ports:
    - '80:80'
    - '443:443' # Ajout du port HTTPS
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx.crt:/etc/nginx/nginx.crt:ro # Montage du certificat SSL
    - ./nginx.key:/etc/nginx/nginx.key:ro # Montage de la clé privée SSL
  depends_on:
    - jenkins
  networks:
    - jenkins_network

networks:
  jenkins_network:

volumes:
  jenkins_home:
