version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data