services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ~/volumes/codecake/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=codecake
      - POSTGRES_USER=codecake
    ports:
      - 192.168.150.4:5432:5432
