version: '3'

services:
  mongoose:
    image: mongo
    container_name: mongoose
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongoose_network

networks:
  mongoose_network:

volumes:
  mongodb_data:
