version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:e
      - jenkinsnet

networks:
  jenkinsnet:

volumes:
  jenkins_home:

  # docker exec -it jenkins /bin/bash
  # cd /var/jenkins_home/secrets/
  # cat /var/jenkins_home/secrets/initialAdminPassword

  # sudo docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
