version: '3'

services:
  jenkins:
    image: georgespasov/docker-jenkins:latest
    container_name: jenkins
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkinsnet
    restart: always

networks:
  jenkinsnet:

volumes:
  jenkins_home:

  # docker exec -it jenkins /bin/bash
  # cd /var/jenkins_home/secrets/
  # cat /var/jenkins_home/secrets/initialAdminPassword

  # sudo docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
