version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - '90001:90001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
