services:
  postgres:
    image: 'mysql:latest'
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=essai
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - '192.168.150.4:3306:3306'
