version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_DB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '0.0.0.0:3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
