version: '3.8'

services:
  mysql:
    image: mysql:8.0 # Utilisez la version souhaitée de MySQL
    container_name: mysql-container
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root # Remplacez par le mot de passe root souhaité
      MYSQL_DATABASE: example_db # Nom de la base de données initiale (optionnel)
      MYSQL_USER: root # Nom d'utilisateur (optionnel)
      MYSQL_PASSWORD: root # Mot de passe de l'utilisateur (optionnel)
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.150.0/24
          gateway: 192.168.150.1

volumes:
  mysql-data:
